---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-ganesha-metrics
  labels:
    app.kubernetes.io/name: nfs-ganesha-metrics
    openshift.io/cluster-monitoring: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nfs-ganesha-metrics-test
    app.kubernetes.io/part-of: nfs-ganesha-metrics
  name: nfs-ganesha-metrics-test
  namespace: nfs-ganesha-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-ganesha-metrics
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: nfs-ganesha-metrics
        app.kubernetes.io/part-of: nfs-ganesha-metrics
    spec:
      hostNetwork: true
      volumes:
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus/
            type: Directory
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - args:
            - --metrics-addr=127.0.0.1:8080
          command:
            - /bin/nfsgmetrics
          env:
            - name: DBUS_SESSION_BUS_ADDRESS
              value: "unix:path=/var/run/dbus/"
            - name: NFS_GANESHA_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NFS_GANESHA_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFS_GANESHA_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NFS_GANESHA_WORKING_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/ssharon/ocs-operator:nfs-ganesha-metrics
          imagePullPolicy: Always
          name: nfs-ganesha-metrics
          volumeMounts:
            - mountPath: /var/run/dbus
              name: dbus-socket
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
