---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-ganesha
  labels:
    control-plane: nfs-ganesha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-ganesha-test
  namespace: nfs-ganesha
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: nfs-ganesha
  template:
    metadata:
      labels:
        control-plane: nfs-ganesha
    spec:
      hostNetwork: true
      volumes:
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus/
            type: Directory
      containers:
        - args:
            - --metrics-addr=127.0.0.1:8080
          command:
            - /bin/nfsgmetrics
          env:
            - name: DBUS_SESSION_BUS_ADDRESS
              value: "unix:path=/var/run/dbus/"
            - name: NFS_GANESHA_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NFS_GANESHA_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFS_GANESHA_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NFS_GANESHA_WORKING_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/ssharon/ocs-operator:nfs-ganesha-metrics
          imagePullPolicy: Always
          name: nfs-ganesha-metrics
          volumeMounts:
            - mountPath: /var/run/dbus
              name: dbus-socket
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
