name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ">=1.17.0"
      - uses: actions/checkout@v2
      - name: Build
        run: make
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ">=1.17.0"
      - uses: actions/checkout@v2
      - name: Install build tools
        run: make build-tools
      - name: Run checks
        run: make check
